PizzaMama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

home/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models

class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):  # def __str__ permet d'afficher le nom dans le pannel admin à la place de pizza Object
        return self.nom 

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

menu/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core import serializers
from .models import Pizza

# Create your views here.
def index(request):
    pizzas = Pizza.objects.all().order_by('prix')
    # # for pizza in pizzas:
    # #     return HttpResponse(pizza.nom + str(pizza.prix))
        
    # pizzas_names_prices = [pizza.nom + ": " + str(pizza.prix) + "€ " for pizza in pizzas]
    # pizzas_names_prices_str = ", ".join(pizzas_names_prices) # permet de concatener et séparer la liste par une , 
    # return HttpResponse("Les pizzas: " + pizzas_names_prices_str)
    return render(request, 'menu/index.html', {'pizzas': pizzas})

def api_get_pizza(request):
    pizzas = Pizza.objects.all().order_by('prix')
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

home/templates/home/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pizza Mama - Home</title>

    <link rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    <div class="center">
        <img src="{% static 'home/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Voir le menu</a>
    </div>
    
</body>
</html>

menu/templates/menu/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Menu des pizzas</title>

    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <div id="logo">
        <a href="{% url 'home:index' %}"><img src="{% static 'menu/images/small_logo.png' %}" alt=""></a>
        
    </div>

    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>
    
    <div class="menu_list">
            {% for pizza in pizzas %}
                <div class="menu_list_item">
                    <span class="menu_list_title">{{ pizza.nom }}</span> 
                    <span class="menu_list_price">{{ pizza.prix | floatformat:2}}€</span>

                    <div class="menu_list_ingredients">{{ pizza.ingredients | capfirst}}</div>
                    {% if pizza.vegetarienne %}
                        <span class="badge_vegetarienne">VEGETARIENNE</span>
                    {% endif %}
                </div>
            {% endfor %}

    </div>
    
</body>
</html>